const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(root, 'assets/js/learn-rlc-data-v3.js'), 'utf8'), context);
vm.runInNewContext(fs.readFileSync(path.join(root, 'assets/js/learn-rlc-enhancements-v1.js'), 'utf8'), context);
vm.runInNewContext(fs.readFileSync(path.join(root, 'assets/js/learn-rlc-revision-v2.js'), 'utf8'), context);
const data = context.window.ShieldioRlcData;
assert.equal(data.version, 6);
assert.equal(data.chapters.length, 16, 'RLC má mít 16 logicky seřazených kapitol');
const text = data.chapters.map(c => `${c.title} ${c.lead} ${c.html}`).join(' ');
for (const required of ['EIA‑96','E192','\\rho\\frac{l}{S}','sériový ztrátový odpor','indukčnost vývodů','potenciometr','odporová dráha','Al₂O₃','elektrolytem','X_L','X_C','Z_L','tau_{RC}','Saturační proud','zvlněný proud','rezonance','A_L','M = k','Transformátor','tečková konvence','derating']) assert.ok(text.includes(required), `chybí ${required}`);
const catalogue = JSON.parse(fs.readFileSync(path.join(root, 'assets/data/learn-questions.json'), 'utf8'));
const rlc = catalogue.questions.find(q => q.slug === 'elektronika-01-linearni-soucastky-r-l-c');
assert.equal(rlc.status, 'complete');
assert.equal(rlc.template, 'rlc-study');
assert.deepEqual(Array.from(data.chapters.slice(0, 5), chapter => chapter.id), ['prehled','rezistor','kondenzator','civka','modely']);
assert.ok(!data.chapters.some(chapter => chapter.id === 'navrh-trafa'), 'návrh síťového transformátoru má být odebrán');
for (const required of ['data-rlc-polarity','data-rlc-derating','data-rlc-tech-frequency','68,75 Ω','Gratuluju']) assert.ok(text.includes(required), `chybí rozšíření ${required}`);
for (const required of ['R → Ω','C → F','L → H','data-rlc-wire','data-rlc-temperature','data-rlc-pot-lab','data-rlc-rc','data-rlc-cap-ac','data-rlc-filter','data-rlc-induction','data-rlc-coil-ac','data-rlc-model-levels','data-rlc-mutual','Rozšíření pro zájemce']) assert.ok(text.includes(required), `chybí revize ${required}`);
console.log(`RLC OK: ${data.chapters.length} kapitol`);
